# Generated by Django 5.2.5 on 2025-09-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('duedate', models.DateField()),
                ('priority', models.CharField(blank=True, null=True)),
                ('status', models.CharField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
